Privacy Policy

[Developer / Company Name] created the application as an application [open source / free / shareware / ad-supported / commercial]. This SERVICE is provided by [Developer / Company Name] [Paid] and is intended to be used as is. This page is used to inform visitors about [my / our] policies regarding the collection, use and disclosure of Personal Information if anyone decides to use [my / our] Service.

If you choose to use [my / our] Service, then you agree to the collection and use of information in relation to this policy. The personal information that [I / We] collects is used to provide and improve the Service. [I / we] will not use or share your information with anyone other than as described in this Privacy Policy. The terms used in this Privacy Policy have the same meaning as in our Terms and Conditions, which are available at the address, unless otherwise defined in this Privacy Policy.

Collection and use of information 

For a better experience when using our Service, [I / We] may require you to provide us with certain personally identifiable information [add here whatever you collect, such as username, address, location, images] Information that [I / We] request will be [stored on your device and will not be collected by [me / us] in any way] / [stored by us and used as described in this privacy policy].

The app uses third party services that may collect information used to identify you. 

Link to the privacy policies of third party service providers used by the application. Google Play Services

Log data

 [I / we] want to inform you that whenever you use [my / our] Service, in the event of an error in the [I / we] application, we collect data and information (through third-party products) on your phone called Data Log. This log data may include information such as your device's IP address, device name, operating system version, application configuration when using [my / our] Service, and the time and date you used the Service. , etc. Statistics.

Cookies

 Cookies are small data files that are commonly used as anonymous unique indicators. They are sent to your browser from the websites you visit and are stored in your device's internal memory. This Service does not explicitly use these "cookies". However, the app may use third-party code and libraries that use cookies to collect information and improve its services. You have the option to accept these cookies and know when a cookie is being sent to your device. You choose to use some cookies.

Service providers

 [I / We] may hire third-party companies and individuals for the following reasons: To facilitate our Service; To provide the Service on our behalf; To provide services related to the Service; or To help us analyze how our Service is used. [I / we] want to inform users of this Service that these third parties have access to their Personal Information. The reason is to carry out their assigned tasks on our behalf. However, they are required not to disclose or use the information for any other purpose.

Safety 

[I / we] value your trust in providing us with your personal information, and we strive to use commercially acceptable means to protect it. But remember that no method of transmission over the Internet or method of electronic storage is 100% secure or reliable, and [I / We] cannot guarantee its absolute security.

Links to other sites

 This Service may contain links to other sites. If you click on a third party link, you will be redirected to that site. Please note that these external sites do not belong to [me / us]. Therefore, [I / we] strongly recommend that you read the Privacy Policy of those websites. [I / we] do not control and are not responsible for the content, privacy policies, or actions of any third party sites or services.

Children's privacy 

These Services are not directed to individuals under the age of 13. [I / we] do not knowingly collect personally identifiable information from children under the age of 13. In the event that [I / we] discover that a child under the age of 13 has provided [me / us] personal information, [I / we] will immediately delete it from our servers. If you are a parent or guardian and you know that your child has provided us with personal information, please contact [me / we] so that [me / we] can take the necessary steps.

Changes to this Privacy Policy

 [I / we] may update our Privacy Policy from time to time. Therefore, you are encouraged to periodically review this page for changes. [I / we] will notify you of any changes by posting a new Privacy Policy on this page. 

This policy is valid from 2021-12-15.

To contact us 

If you have any questions or suggestions regarding [my / our] Privacy Policy, please do not hesitate to contact [me / us] at. (helpforplayers@gmail.com) 
